name: Build and Upload Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_path: build/fast-tfm
          - os: windows-latest
            artifact_path: build/Release/fast-tfm.exe

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.artifact_path }}
